-- Seed Judo health insurance R6 active master.
-- Rollback: supabase/rollbacks/20260524000100_seed_judo_hi_r6_active_master_rollback.sql

insert into public.insurance_fee_sources (
  source_id,
  title,
  publisher,
  source_url,
  document_date,
  effective_from,
  effective_to,
  target_domain,
  reliability,
  notes
) values (
  'MHLW_JUDO_HI_R6_FINAL_20240529',
  '柔道整復師の施術料金の算定方法',
  '厚生労働省 / 九州厚生局',
  'https://kouseikyoku.mhlw.go.jp/kyushu/shinsei/shido_kansa/judo/000339906.pdf',
  '2024-05-29',
  '2024-06-01',
  null,
  'judo_health_insurance',
  'official',
  '最終改正 令和6年5月29日 保発0529第4号。Tiramisuでは現在以降の経営分析用概算根拠として使用する。'
)
on conflict (source_id) do update set
  title = excluded.title,
  publisher = excluded.publisher,
  source_url = excluded.source_url,
  document_date = excluded.document_date,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  target_domain = excluded.target_domain,
  reliability = excluded.reliability,
  notes = excluded.notes,
  updated_at = now()
where (
  public.insurance_fee_sources.title,
  public.insurance_fee_sources.publisher,
  public.insurance_fee_sources.source_url,
  public.insurance_fee_sources.document_date,
  public.insurance_fee_sources.effective_from,
  public.insurance_fee_sources.effective_to,
  public.insurance_fee_sources.target_domain,
  public.insurance_fee_sources.reliability,
  public.insurance_fee_sources.notes
) is distinct from (
  excluded.title,
  excluded.publisher,
  excluded.source_url,
  excluded.document_date,
  excluded.effective_from,
  excluded.effective_to,
  excluded.target_domain,
  excluded.reliability,
  excluded.notes
);

insert into public.insurance_fee_source_snapshots (
  source_id,
  source_url,
  document_title,
  document_date,
  content_hash,
  file_path_or_storage_key,
  mime_type,
  byte_size,
  notes
) values (
  'MHLW_JUDO_HI_R6_FINAL_20240529',
  'https://kouseikyoku.mhlw.go.jp/kyushu/shinsei/shido_kansa/judo/000339906.pdf',
  '柔道整復師の施術料金の算定方法',
  '2024-05-29',
  'c2797b42b9ec4558ddc4969a795fbd6e4622e45d1182ad2c02378f788a67ddd3',
  'mhlw/kyushu/judo/000339906.pdf',
  'application/pdf',
  165498,
  '2026-05-24に根拠仕様へ記録したSHA-256。'
)
on conflict (source_id, content_hash) do update set
  source_url = excluded.source_url,
  document_title = excluded.document_title,
  document_date = excluded.document_date,
  file_path_or_storage_key = excluded.file_path_or_storage_key,
  mime_type = excluded.mime_type,
  byte_size = excluded.byte_size,
  notes = excluded.notes
where (
  public.insurance_fee_source_snapshots.source_url,
  public.insurance_fee_source_snapshots.document_title,
  public.insurance_fee_source_snapshots.document_date,
  public.insurance_fee_source_snapshots.file_path_or_storage_key,
  public.insurance_fee_source_snapshots.mime_type,
  public.insurance_fee_source_snapshots.byte_size,
  public.insurance_fee_source_snapshots.notes
) is distinct from (
  excluded.source_url,
  excluded.document_title,
  excluded.document_date,
  excluded.file_path_or_storage_key,
  excluded.mime_type,
  excluded.byte_size,
  excluded.notes
);

insert into public.insurance_fee_warning_definitions (
  warning_code,
  severity,
  message,
  applies_to_profession_type,
  applies_to_payer_context_code,
  auto_block_calculation,
  manual_review_required,
  is_active,
  sort_order
) values
  (
    'JUDO_HI_CONDITION_REVIEW_REQUIRED',
    'needs_review',
    '柔道整復・健康保険の算定条件を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    100
  ),
  (
    'JUDO_HI_BODY_PART_RULE_REVIEW',
    'needs_review',
    '部位数、3部位目60%、4部位目以降の取扱いを確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    110
  ),
  (
    'JUDO_HI_INJURY_DATE_REVIEW',
    'needs_review',
    '受傷日からの除外期間または算定可能期間を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    120
  ),
  (
    'JUDO_HI_LONG_TERM_REVIEW',
    'needs_review',
    '長期・頻回の逓減条件を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    130
  ),
  (
    'JUDO_HI_MONTHLY_LIMIT_REVIEW',
    'needs_review',
    '月内算定回数の制限を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    140
  ),
  (
    'JUDO_HI_HOME_VISIT_REVIEW',
    'needs_review',
    '往療の距離、時間帯、天候、難路等の条件を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    150
  ),
  (
    'JUDO_HI_PHYSICIAN_CONSENT_REVIEW',
    'needs_review',
    '医師同意または医師依頼の要否を確認してください。',
    'judo',
    'insurance',
    false,
    true,
    true,
    160
  )
on conflict (warning_code) do update set
  severity = excluded.severity,
  message = excluded.message,
  applies_to_profession_type = excluded.applies_to_profession_type,
  applies_to_payer_context_code = excluded.applies_to_payer_context_code,
  auto_block_calculation = excluded.auto_block_calculation,
  manual_review_required = excluded.manual_review_required,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now()
where (
  public.insurance_fee_warning_definitions.severity,
  public.insurance_fee_warning_definitions.message,
  public.insurance_fee_warning_definitions.applies_to_profession_type,
  public.insurance_fee_warning_definitions.applies_to_payer_context_code,
  public.insurance_fee_warning_definitions.auto_block_calculation,
  public.insurance_fee_warning_definitions.manual_review_required,
  public.insurance_fee_warning_definitions.is_active,
  public.insurance_fee_warning_definitions.sort_order
) is distinct from (
  excluded.severity,
  excluded.message,
  excluded.applies_to_profession_type,
  excluded.applies_to_payer_context_code,
  excluded.auto_block_calculation,
  excluded.manual_review_required,
  excluded.is_active,
  excluded.sort_order
);

insert into public.insurance_fee_schedules (
  schedule_code,
  profession_type,
  payer_context_code,
  schedule_name,
  effective_from,
  effective_to,
  schedule_status,
  source_id,
  source_snapshot_hash,
  revision_reason,
  is_locked,
  notes
) values (
  'JUDO_HI_R6_202410_ACTIVE',
  'judo',
  'insurance',
  '柔道整復 健康保険 令和6年改定 現行料金',
  '2024-10-01',
  null,
  'active',
  'MHLW_JUDO_HI_R6_FINAL_20240529',
  'c2797b42b9ec4558ddc4969a795fbd6e4622e45d1182ad2c02378f788a67ddd3',
  '令和6年5月29日付確定通知に基づく現行料金マスタ',
  false,
  '現在以降の経営分析用概算に使う統合版。請求確定額ではない。'
)
on conflict (schedule_code) do nothing;

with seed_items (
  item_code,
  item_name,
  official_label,
  category,
  amount_yen,
  unit,
  billing_scope,
  calculation_basis,
  applicable_conditions_json,
  exclusion_conditions_json,
  required_inputs_json,
  warning_codes_json,
  auto_calculation_allowed,
  sort_order
) as (
  values
    (
      'JUDO_HI_INITIAL_EXAM',
      '初検料',
      '初検料',
      'visit_base',
      1550,
      'visit',
      'treatment_day',
      '初検時',
      '{"visit_stage":"first_visit"}'::jsonb,
      '{}'::jsonb,
      '{"visit_stage_code":true}'::jsonb,
      '[]'::jsonb,
      true,
      10
    ),
    (
      'JUDO_HI_INITIAL_CONSULT_SUPPORT',
      '初検時相談支援料',
      '初検時相談支援料',
      'visit_addon',
      100,
      'visit',
      'treatment_day',
      '患者へ留意事項等を説明し、施術録に記載した場合',
      '{"visit_stage":"first_visit","record_required":true}'::jsonb,
      '{}'::jsonb,
      '{"visit_stage_code":true,"record_note":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      20
    ),
    (
      'JUDO_HI_HOME_VISIT',
      '往療料',
      '往療料',
      'home_visit',
      2300,
      'visit',
      'home_visit',
      '往療基本額',
      '{"home_visit":true}'::jsonb,
      '{}'::jsonb,
      '{"home_visit":true}'::jsonb,
      '["JUDO_HI_HOME_VISIT_REVIEW"]'::jsonb,
      false,
      30
    ),
    (
      'JUDO_HI_HOME_VISIT_OVER_4KM',
      '往療料 片道4km超',
      '往療距離が片道4kmを超える場合の往療料',
      'home_visit',
      2550,
      'visit',
      'home_visit',
      '片道4km超の場合',
      '{"home_visit":true,"one_way_distance_km_gt":4}'::jsonb,
      '{}'::jsonb,
      '{"home_visit":true,"one_way_distance_km":true}'::jsonb,
      '["JUDO_HI_HOME_VISIT_REVIEW"]'::jsonb,
      false,
      31
    ),
    (
      'JUDO_HI_INITIAL_AFTER_HOURS_ADDON',
      '時間外初検加算',
      '表示施術時間外に初検',
      'visit_addon',
      540,
      'visit',
      'treatment_day',
      '表示施術時間外の初検加算',
      '{"visit_stage":"first_visit","after_hours":true}'::jsonb,
      '{}'::jsonb,
      '{"visit_stage_code":true,"time_classification":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      40
    ),
    (
      'JUDO_HI_INITIAL_HOLIDAY_ADDON',
      '休日初検加算',
      '休日に初検',
      'visit_addon',
      1560,
      'visit',
      'treatment_day',
      '休日初検加算',
      '{"visit_stage":"first_visit","holiday":true}'::jsonb,
      '{}'::jsonb,
      '{"visit_stage_code":true,"holiday":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      41
    ),
    (
      'JUDO_HI_INITIAL_LATE_NIGHT_ADDON',
      '深夜初検加算',
      '午後10時から午前6時までに初検',
      'visit_addon',
      3120,
      'visit',
      'treatment_day',
      '深夜初検加算',
      '{"visit_stage":"first_visit","late_night":true}'::jsonb,
      '{}'::jsonb,
      '{"visit_stage_code":true,"time_classification":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      42
    ),
    (
      'JUDO_HI_HOME_VISIT_SPECIAL_ADDON',
      '夜間等往療加算',
      '夜間・難路・暴風雨時・暴風雪時の往療',
      'home_visit_addon',
      null,
      'percent',
      'home_visit',
      '往療所定金額の100%を加算',
      '{"home_visit":true,"special_home_visit_condition":true}'::jsonb,
      '{}'::jsonb,
      '{"home_visit":true,"special_home_visit_condition":true}'::jsonb,
      '["JUDO_HI_HOME_VISIT_REVIEW"]'::jsonb,
      false,
      43
    ),
    (
      'JUDO_HI_RE_EXAM',
      '再検料',
      '再検料',
      'visit_base',
      410,
      'visit',
      'treatment_day',
      '初回後療日に限り算定',
      '{"first_aftercare_day_only":true}'::jsonb,
      '{}'::jsonb,
      '{"visit_ordinal_in_episode":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      50
    ),
    (
      'JUDO_HI_FRACTURE_REDUCTION_CLAVICLE_RIB',
      '骨折 整復料 鎖骨・肋骨',
      '鎖骨又は肋骨 骨折整復料',
      'fracture_reduction',
      5500,
      'body_part',
      'injury_body_part',
      '鎖骨又は肋骨の骨折整復料',
      '{"injury_type":"fracture","body_part_group":"clavicle_or_rib"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      100
    ),
    (
      'JUDO_HI_FRACTURE_REDUCTION_MAJOR_LONG_BONE',
      '骨折 整復料 長管骨',
      '上腕骨・前腕骨・大腿骨・下腿骨 骨折整復料',
      'fracture_reduction',
      11800,
      'body_part',
      'injury_body_part',
      '上腕骨・前腕骨・大腿骨・下腿骨の骨折整復料',
      '{"injury_type":"fracture","body_part_group":"major_long_bone"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      101
    ),
    (
      'JUDO_HI_FRACTURE_REDUCTION_SMALL_BONE',
      '骨折 整復料 手足骨等',
      '手根骨・足根骨・中手骨・中足骨・指骨 骨折整復料',
      'fracture_reduction',
      5500,
      'body_part',
      'injury_body_part',
      '手足骨等の骨折整復料',
      '{"injury_type":"fracture","body_part_group":"small_bone"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      102
    ),
    (
      'JUDO_HI_POST_FRACTURE',
      '骨折 後療料',
      '骨折 後療料',
      'aftercare',
      850,
      'body_part',
      'injury_body_part',
      '骨折の後療料',
      '{"injury_type":"fracture"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_LONG_TERM_REVIEW"]'::jsonb,
      false,
      110
    ),
    (
      'JUDO_HI_POST_FRACTURE_CONTRACTURE',
      '骨折 後療料 拘縮2関節以上',
      '医師により後療を依頼され拘縮が2関節以上に及ぶ場合の骨折後療料',
      'aftercare',
      1090,
      'body_part',
      'injury_body_part',
      '医師依頼かつ拘縮2関節以上',
      '{"injury_type":"fracture","contracture_joint_count_gte":2,"physician_request":true}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true,"physician_request":true}'::jsonb,
      '["JUDO_HI_PHYSICIAN_CONSENT_REVIEW","JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      111
    ),
    (
      'JUDO_HI_INCOMPLETE_FRACTURE_FIXATION_CLAVICLE_STERNUM_RIB',
      '不全骨折 固定料 鎖骨・胸骨・肋骨',
      '鎖骨・胸骨・肋骨 不全骨折固定料',
      'fixation',
      4100,
      'body_part',
      'injury_body_part',
      '鎖骨・胸骨・肋骨の不全骨折固定料',
      '{"injury_type":"incomplete_fracture","body_part_group":"clavicle_sternum_rib"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      120
    ),
    (
      'JUDO_HI_INCOMPLETE_FRACTURE_FIXATION_PELVIS_FEMUR',
      '不全骨折 固定料 骨盤・大腿骨',
      '骨盤・大腿骨 不全骨折固定料',
      'fixation',
      9500,
      'body_part',
      'injury_body_part',
      '骨盤・大腿骨の不全骨折固定料',
      '{"injury_type":"incomplete_fracture","body_part_group":"pelvis_or_femur"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      121
    ),
    (
      'JUDO_HI_INCOMPLETE_FRACTURE_FIXATION_ARM_LEG_PATELLA',
      '不全骨折 固定料 上腕骨・前腕骨・下腿骨・膝蓋骨',
      '上腕骨・前腕骨・下腿骨・膝蓋骨 不全骨折固定料',
      'fixation',
      7300,
      'body_part',
      'injury_body_part',
      '上腕骨・前腕骨・下腿骨・膝蓋骨の不全骨折固定料',
      '{"injury_type":"incomplete_fracture","body_part_group":"arm_leg_patella"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      122
    ),
    (
      'JUDO_HI_INCOMPLETE_FRACTURE_FIXATION_SMALL_BONE',
      '不全骨折 固定料 手足骨等',
      '手根骨・足根骨・中手骨・中足骨・指骨 不全骨折固定料',
      'fixation',
      3900,
      'body_part',
      'injury_body_part',
      '手足骨等の不全骨折固定料',
      '{"injury_type":"incomplete_fracture","body_part_group":"small_bone"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      123
    ),
    (
      'JUDO_HI_POST_INCOMPLETE_FRACTURE',
      '不全骨折 後療料',
      '不全骨折 後療料',
      'aftercare',
      720,
      'body_part',
      'injury_body_part',
      '不全骨折の後療料',
      '{"injury_type":"incomplete_fracture"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_LONG_TERM_REVIEW"]'::jsonb,
      false,
      130
    ),
    (
      'JUDO_HI_POST_INCOMPLETE_FRACTURE_CONTRACTURE',
      '不全骨折 後療料 拘縮2関節以上',
      '医師により後療を依頼され拘縮が2関節以上に及ぶ場合の不全骨折後療料',
      'aftercare',
      960,
      'body_part',
      'injury_body_part',
      '医師依頼かつ拘縮2関節以上',
      '{"injury_type":"incomplete_fracture","contracture_joint_count_gte":2,"physician_request":true}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true,"physician_request":true}'::jsonb,
      '["JUDO_HI_PHYSICIAN_CONSENT_REVIEW","JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      131
    ),
    (
      'JUDO_HI_DISLOCATION_REDUCTION_JAW',
      '脱臼 整復料 顎関節',
      '顎関節 脱臼整復料',
      'dislocation_reduction',
      2600,
      'body_part',
      'injury_body_part',
      '顎関節脱臼の整復料',
      '{"injury_type":"dislocation","body_part_group":"jaw"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      140
    ),
    (
      'JUDO_HI_DISLOCATION_REDUCTION_SHOULDER',
      '脱臼 整復料 肩関節',
      '肩関節 脱臼整復料',
      'dislocation_reduction',
      8200,
      'body_part',
      'injury_body_part',
      '肩関節脱臼の整復料',
      '{"injury_type":"dislocation","body_part_group":"shoulder"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      141
    ),
    (
      'JUDO_HI_DISLOCATION_REDUCTION_HIP',
      '脱臼 整復料 股関節',
      '股関節 脱臼整復料',
      'dislocation_reduction',
      9300,
      'body_part',
      'injury_body_part',
      '股関節脱臼の整復料',
      '{"injury_type":"dislocation","body_part_group":"hip"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      142
    ),
    (
      'JUDO_HI_DISLOCATION_REDUCTION_OTHER',
      '脱臼 整復料 肘・膝・手足指関節等',
      '肘関節・膝関節・手関節・足関節・指関節 脱臼整復料',
      'dislocation_reduction',
      3900,
      'body_part',
      'injury_body_part',
      '肘・膝・手足指関節等の脱臼整復料',
      '{"injury_type":"dislocation","body_part_group":"other_joint"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      143
    ),
    (
      'JUDO_HI_POST_DISLOCATION',
      '脱臼 後療料',
      '脱臼 後療料',
      'aftercare',
      720,
      'body_part',
      'injury_body_part',
      '脱臼の後療料',
      '{"injury_type":"dislocation"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_LONG_TERM_REVIEW"]'::jsonb,
      false,
      150
    ),
    (
      'JUDO_HI_FIRST_CONTUSION',
      '打撲 施療料',
      '打撲 施療料',
      'contusion_sprain',
      760,
      'body_part',
      'injury_body_part',
      '打撲の初回施療料',
      '{"injury_type":"contusion","first_treatment":true}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      200
    ),
    (
      'JUDO_HI_FIRST_SPRAIN',
      '捻挫 施療料',
      '捻挫 施療料',
      'contusion_sprain',
      760,
      'body_part',
      'injury_body_part',
      '捻挫の初回施療料',
      '{"injury_type":"sprain","first_treatment":true}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      201
    ),
    (
      'JUDO_HI_POST_CONTUSION',
      '打撲 後療料',
      '打撲 後療料',
      'contusion_sprain',
      505,
      'body_part',
      'injury_body_part',
      '打撲の後療料',
      '{"injury_type":"contusion"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_LONG_TERM_REVIEW"]'::jsonb,
      false,
      210
    ),
    (
      'JUDO_HI_POST_SPRAIN',
      '捻挫 後療料',
      '捻挫 後療料',
      'contusion_sprain',
      505,
      'body_part',
      'injury_body_part',
      '捻挫の後療料',
      '{"injury_type":"sprain"}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true}'::jsonb,
      '["JUDO_HI_BODY_PART_RULE_REVIEW","JUDO_HI_LONG_TERM_REVIEW"]'::jsonb,
      false,
      211
    ),
    (
      'JUDO_HI_WARM_COMPRESS',
      '温罨法料',
      '温罨法料',
      'modality',
      75,
      'body_part',
      'injury_body_part',
      '後療で併施。除外期間あり',
      '{"modality":"warm_compress"}'::jsonb,
      '{"injury_date_exclusion_days_required":true}'::jsonb,
      '{"injury_type":true,"body_part":true,"injury_date":true}'::jsonb,
      '["JUDO_HI_INJURY_DATE_REVIEW","JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      300
    ),
    (
      'JUDO_HI_COLD_COMPRESS',
      '冷罨法料',
      '冷罨法料',
      'modality',
      85,
      'body_part',
      'injury_body_part',
      '対象傷病・対象期間の制限あり',
      '{"modality":"cold_compress"}'::jsonb,
      '{"injury_date_window_required":true}'::jsonb,
      '{"injury_type":true,"body_part":true,"injury_date":true}'::jsonb,
      '["JUDO_HI_INJURY_DATE_REVIEW","JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      301
    ),
    (
      'JUDO_HI_ELECTROTHERAPY',
      '電療料',
      '電療料',
      'modality',
      33,
      'body_part',
      'injury_body_part',
      '後療で器具を使用。除外期間あり',
      '{"modality":"electrotherapy"}'::jsonb,
      '{"injury_date_exclusion_days_required":true}'::jsonb,
      '{"injury_type":true,"body_part":true,"injury_date":true}'::jsonb,
      '["JUDO_HI_INJURY_DATE_REVIEW","JUDO_HI_BODY_PART_RULE_REVIEW"]'::jsonb,
      false,
      302
    ),
    (
      'JUDO_HI_SPLINT_ADDON_INITIAL',
      '金属副子等使用加算',
      '金属副子等使用加算',
      'material_addon',
      1000,
      'case',
      'injury_body_part',
      '整復料・固定料への加算',
      '{"splint_initial":true}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true,"splint_required":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      400
    ),
    (
      'JUDO_HI_SPLINT_ADDON_REPLACEMENT',
      '金属副子等交換加算',
      '金属副子等交換加算',
      'material_addon',
      1000,
      'case',
      'injury_body_part',
      '交換が必要な場合、2回まで',
      '{"splint_replacement":true,"max_count":2}'::jsonb,
      '{}'::jsonb,
      '{"injury_type":true,"body_part":true,"replacement_count":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      401
    ),
    (
      'JUDO_HI_EXERCISE_AFTERCARE',
      '柔道整復運動後療料',
      '柔道整復運動後療料',
      'exercise_aftercare',
      320,
      'day',
      'treatment_day',
      '骨折・不全骨折・脱臼、負傷日から15日間を除く等の条件あり',
      '{"injury_type_in":["fracture","incomplete_fracture","dislocation"],"exercise_aftercare":true}'::jsonb,
      '{"injury_date_exclusion_days":15}'::jsonb,
      '{"injury_type":true,"injury_date":true}'::jsonb,
      '["JUDO_HI_INJURY_DATE_REVIEW","JUDO_HI_PHYSICIAN_CONSENT_REVIEW"]'::jsonb,
      false,
      410
    ),
    (
      'JUDO_HI_INFORMATION_PROVISION',
      '施術情報提供料',
      '施術情報提供料',
      'document_addon',
      1000,
      'case',
      'care_episode',
      '応急施術後に文書を添え保険医療機関へ紹介した場合',
      '{"information_provision":true}'::jsonb,
      '{}'::jsonb,
      '{"referral_document":true,"medical_institution_referral":true}'::jsonb,
      '["JUDO_HI_CONDITION_REVIEW_REQUIRED"]'::jsonb,
      false,
      420
    ),
    (
      'JUDO_HI_STATEMENT_SYSTEM_ADDON',
      '明細書発行体制加算',
      '明細書発行体制加算',
      'document_addon',
      10,
      'month',
      'monthly',
      '2024-10-01以降、要件を満たす場合に月1回まで',
      '{"statement_system":true,"max_count_per_month":1}'::jsonb,
      '{}'::jsonb,
      '{"clinic_statement_system_enabled":true}'::jsonb,
      '["JUDO_HI_MONTHLY_LIMIT_REVIEW"]'::jsonb,
      false,
      430
    )
)
insert into public.insurance_fee_items (
  schedule_code,
  item_code,
  item_name,
  official_label,
  category,
  amount_yen,
  unit,
  billing_scope,
  calculation_basis,
  applicable_conditions_json,
  exclusion_conditions_json,
  required_inputs_json,
  warning_codes_json,
  manual_amount_required,
  auto_calculation_allowed,
  source_id,
  source_snapshot_hash,
  confidence,
  sort_order
)
select
  'JUDO_HI_R6_202410_ACTIVE',
  seed_items.item_code,
  seed_items.item_name,
  seed_items.official_label,
  seed_items.category,
  seed_items.amount_yen,
  seed_items.unit,
  seed_items.billing_scope,
  seed_items.calculation_basis,
  seed_items.applicable_conditions_json,
  seed_items.exclusion_conditions_json,
  seed_items.required_inputs_json,
  seed_items.warning_codes_json,
  false,
  seed_items.auto_calculation_allowed,
  'MHLW_JUDO_HI_R6_FINAL_20240529',
  'c2797b42b9ec4558ddc4969a795fbd6e4622e45d1182ad2c02378f788a67ddd3',
  'high',
  seed_items.sort_order
from seed_items
join public.insurance_fee_schedules schedule
  on schedule.schedule_code = 'JUDO_HI_R6_202410_ACTIVE'
  and schedule.is_locked = false
on conflict (schedule_code, item_code) do nothing;

update public.insurance_fee_schedules
set is_locked = true,
    updated_at = now()
where schedule_code = 'JUDO_HI_R6_202410_ACTIVE'
  and is_locked = false;
